/*
 * Automatically Generated by DataDec
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <assert.h>
#include "symboltable.h"



map map_cons( string label, int address, map tail )
{
	map	new = NEW(map);
	assert( new != NULL );
	new->label = label;
	new->address = address;
	new->tail = tail;
	return new;
}


kind_of_map map_kind( map this )
{
	if( this == NULL )
	{
		return map_is_nil;
	}
	return map_is_cons;
}


void get_map_cons( map this, string *label, int *address, map *tail )
{
	*label = this->label;
	*address = this->address;
	*tail = this->tail;
}


void print_map( FILE *f, map p )
{
	if( p == NULL )
	{
		fputs( "nil", f );
		return;
	}
	string r = (p->label);

	fputs( "cons", f );
	fputc( '(', f );
	printf("%s\n", r);
	fputs( r, f );
	fputc( ',', f );
	fprintf( f, "%d", p->address );
	fputc( ',', f );
	print_map( f, p->tail );
	fputc( ')', f );
}

void print_map2(map p) {
	printf("Label %s, address 0x%08x\n", p->label, p->address);
	if (p -> tail != NULL) {
		print_map2(p->tail);
	}

}

