/*
 * Automatically Generated by DataDec
 */

typedef char *string;

#define NEW(t) ((t)malloc(sizeof(struct t)))


struct map;
typedef struct map *map;


/* ---- Type map ---- */

typedef enum {
	map_is_nil,
	map_is_cons,
} kind_of_map;

struct map {
	string	label;
	int	address;
	map	tail;
};


/* Prototypes for all types */

#define map_nil() ((map)NULL)
extern map map_cons( string , int , map );
extern kind_of_map map_kind( map );
extern void get_map_cons( map , string * , int * , map * );
extern void print_map( FILE *, map );
void print_map2(map p);
